modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (31 is current forge version)
credits="Drachenbauer32" #optional
authors="Drachenbauer32" #optional

[[mods]] #mandatory
modId="coloredflowerpotsmod" #mandatory
version="1.0" #mandatory
displayName="Colored Flowerpots Mod" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
adds flowerpots in the 16 concrete-colors.
All plants can be placed in the new colorful pots.
Bees now accept all potted variants of the flowers, wich they normally accept.
'''

[[dependencies.coloredflowerpots]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
    
# Here's another dependency
[[dependencies.coloredflowerpots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
